openapi: 3.0.3
info:
  title: WASA-Exam
  description: Program that will hopefully pass the exam.
  version: 1.0.0

security: []   

tags:
  - name: Auth
    description: Endpoints for logging.
  - name: Profile
    description: Endpoints for managing user operations.
  - name: Conversation
    description: Endpoints for managing conversation operations.
  - name: Message
    description: Endpoints for managing message operations.
  - name: Reaction
    description: Endpoints for adding or removing reactions or comments on messages.
  - name: Group
    description: Endpoints for managing group operations.

paths:
  /doLogin:
    post:
      tags:
        - Auth
      summary: Log in or create an account
      description: |
        Logs in the user. 
        If the user doesn't exist, it will be created and an identifier is returned.
        If the user exists, the identifier is returned.
      operationId: doLogin
      security: []    
      requestBody:
        description: User details
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Maria
                  minLength: 3
                  maxLength: 20
              required: [name]
      responses:
        "200":
          description: User successfully logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    type: string
                    example: "abcdef012345"
        "201":
          description: User successfully created
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    type: string
                    example: "abcdef012345"
        "400":
          description: Invalid input data, failed to login
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid input data"

  /user/changename:
    put:
      tags:
        - Profile
      summary: Change your username
      description: Updates the username of the logged-in user if the new username is valid and not already taken.
      operationId: setMyUserName
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Username'
      responses:
        '200':
          description: Username updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid or already taken username
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Username already taken"


  /user/conversations:
    get:
      tags:
        - Conversation
      summary: Get user's conversations
      description: Returns all conversations of the logged-in user
      operationId: getMyConversations
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of conversations of the user
          content:
            application/json:
              schema:
                description: Array of objects each representing a conversation
                type: array
                items:
                  $ref: '#/components/schemas/Conversation'
        '400':
          description: Failed to retrieve conversations
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Failed to retrieve conversations"
  /conversation/{id}:
    get:
      tags:
        - Conversation
      summary: Get a single conversation
      description: Retrieve a single conversation including participants and messages.
      operationId: getConversation
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          description: The unique ID of the conversation
          required: true
          schema:
            type: string
            example: "conv123"
      responses:
        '200':
          description: Conversation details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conversation'
        '404':
          description: Conversation not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Conversation not found"
        '400':
          description: Invalid conversation ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid conversation ID"
  /conversation/{id}/sendMessage:
    post:
      tags:
        - Message
      summary: Send a new message in a conversation
      description: Adds a new message to the specified conversation.
      operationId: sendMessage
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          description: The ID of the conversation
          required: true
          schema:
            type: string
            example: "conv123"
      requestBody:
        description: Message to send
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: object
                  required:
                    - type
                    - value
                  properties:
                    type:
                      type: string
                      enum: [text, photo]
                      description: Type of message
                    value:
                      type: string
                      description: Text content or URL to photo

      responses:
        '201':
          description: Message sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'

        '404':
          description: Conversation not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Conversation not found"
        '400':
          description: Invalid request (e.g., missing content)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid message data"
  /conversations/{sourceConversationId}/messages/{messageId}/forward:
    post:
      tags:
        - Message
      summary: Forward a message
      description: Forwards an existing message from one conversation to another.
      operationId: forwardMessage
      security:
        - BearerAuth: []
      parameters:
        - name: sourceConversationId
          in: path
          required: true
          description: ID of the conversation containing the original message
          schema:
            type: string
            example: "conv123"
        - name: messageId
          in: path
          required: true
          description: ID of the message to forward
          schema:
            type: string
            example: "msg789"
      requestBody:
        required: true
        description: Target conversation to forward the message to
        content:
          application/json:
            schema:
              type: object
              required:
                - targetConversationId
              properties:
                targetConversationId:
                  type: string
                  description: ID of the conversation to forward the message to
                  example: "conv456"
      responses:
        '201':
          description: Message successfully forwarded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '404':
          description: Conversation or message not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Conversation or message not found"
        '400':
          description: Invalid request (e.g., missing targetConversationId)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid request data"
  /conversations/{conversationId}/messages/{messageId}:
    delete:
      tags:
        - Message
      summary: Delete a message
      description: Deletes a message from a conversation.
      operationId: deleteMessage
      security:
        - BearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          description: The ID of the conversation containing the message.
          schema:
            type: string
            example: "conv123"
        - name: messageId
          in: path
          required: true
          description: The ID of the message to delete.
          schema:
            type: string
            example: "msg789"
      responses:
        '200':
          description: Message deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Message deleted"
        '403':
          description: User is not allowed to delete this message
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "You cannot delete this message"
        '404':
          description: Conversation or message not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Message not found"
        '400':
          description: Invalid IDs (wrong format, empty, etc.)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid message ID"






components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Username:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          minLength: 3
          maxLength: 20
          example: "Alex"

    User:
      type: object
      description: Represents a user
      required:
        - id
        - username
      properties:
        id:
          type: string
          description: Unique identifier for the user, given upon account creation
          example: "user123"
          minLength: 1
          maxLength: 30
        username:
          $ref: '#/components/schemas/Username'
        profilePhoto:
          type: string
          format: byte
          nullable: true
          description: Optional Base64-encoded image data

    Message:
      type: object
      description: A message sent in a conversation
      required:
        - id
        - sender
        - content
        - timestamp
        - message_status
      properties:
        id:
          type: string
          description: Unique identifier for the message
          example: "msg123"
          minLength: 1
          maxLength: 36
        sender:
          $ref: '#/components/schemas/User'
        content:
          type: object
          description: Content of the message
          required:
            - type
            - value
          properties:
            type:
              type: string
              enum: [text, photo]
              description: Type of message
            value:
              type: string
              description: Text content or URL to photo
        timestamp:
          type: string
          format: date-time
          description: Timestamp of when the message was sent
          example: "2025-12-10T11:45:00Z"
        message_status:
          type: string
          enum: [sent, delivered, read]
          description: Status of the message
        reactions:
          type: array
          description: Reactions applied to this message
          items:
            href: '#/components/schemas/Reaction'
          nullable: true

    Conversation:
      type: object
      description: Conversation belonging to a user
      required:
        - id
        - name
        - isGroup
      properties:
        id:
          type: string
          example: "conv123"
        name:
          type: string
          example: "WASA Group Chat"
        groupPhoto:
          type: string
          format: byte
          nullable: true
          description: Group photo
        isGroup:
          type: boolean
          description: True if this is a group conversation, false if private
          example: true
        lastMessage:
          $ref: '#/components/schemas/Message'
          nullable: true
        participants:
          type: array
          description: List of participants
          items:
            $ref: '#/components/schemas/User'
        messages:
          type: array
          description: List of messages sent in the conversation
          items:
            $ref: '#/components/schemas/Message'
          nullable: true
 
