openapi: 3.0.3
info:
  title: WASA-Exam
  description: API for the WASA Exam project.
  version: 1.0.0

security: []

tags:
  - name: Auth
  - name: Profile
  - name: Conversation
  - name: Message
  - name: Reaction
  - name: Group

paths:
  /doLogin:
    post:
      tags:
        - Auth
      summary: Log in or create account
      operationId: doLogin
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  minLength: 3
                  maxLength: 20
                  example: "Maria"
      responses:
        "200":
          description: Logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    type: string
                    example: "user123token"
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    type: string

  /user/{id}/changename:
    put:
      tags:
        - Profile
      summary: Change username
      operationId: setMyUserName
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Username'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Error

  /user/{id}/conversations:
    get:
      tags:
        - Conversation
      summary: Get conversations
      operationId: getMyConversations
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List conversations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Conversation'

  /conversation/{id}:
    get:
      tags:
        - Conversation
      summary: Get single conversation
      operationId: getConversation
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conversation'

  /conversation/{id}/sendMessage:
    post:
      tags:
        - Message
      summary: Send message
      operationId: sendMessage
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: object
                  required:
                    - type
                    - value
                  properties:
                    type:
                      type: string
                      enum: [text, photo]
                    value:
                      type: string
      responses:
        '201':
          description: Sent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'

  /conversation/{conversationId}/messages/{messageId}:
    delete:
      tags:
        - Message
      summary: Delete message
      operationId: deleteMessage
      security:
        - BearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
        - name: messageId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Deleted

  /conversation/{sourceConversationId}/messages/{messageId}/forward:
    post:
      tags:
        - Message
      summary: Forward message
      operationId: forwardMessage
      security:
        - BearerAuth: []
      parameters:
        - name: sourceConversationId
          in: path
          required: true
          schema:
            type: string
        - name: messageId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - targetConversationId
              properties:
                targetConversationId:
                  type: string
      responses:
        '201':
          description: Forwarded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'

  /conversations/{conversationId}/messages/{messageId}/reactions:
    post:
      tags: [Reaction]
      summary: Add a reaction to a message
      operationId: commentMessage
      security:
        - BearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
        - name: messageId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [type]
              properties:
                type:
                  type: string
                  enum: [like, heart, laugh,sad_face,angry_face]
                  description: Type of reaction to add
      responses:
        '200':
          description: Reaction added successfully
        '400':
          description: Invalid request 
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid reaction"
        '404':
          description: Message or conversation not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Message not found"


  /conversations/{conversationId}/messages/{messageId}/reactions/{type}:
    delete:
      tags: [Reaction]
      summary: Remove a reaction from a message
      operationId: uncommentMessage
      security:
        - BearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
        - name: messageId
          in: path
          required: true
          schema:
            type: string
        - name: type
          in: path
          required: true
          schema:
            type: string
            enum: [like, heart, laugh,sad_face,angry_face]
    responses:
      '200':
        description: Reaction removed successfully
      '400':
        description: Invalid request (e.g., user hasn’t reacted)
        content:
          application/json:
            schema:
              type: object
              properties:
                error:
                  type: string
                  example: "You haven’t reacted with this type"
      '404':
        description: Message or conversation not found
        content:
          application/json:
            schema:
              type: object
              properties:
                error:
                  type: string
                  example: "Message not found"


  /conversations/{conversationId}/participants/{userId}:
    put:
      tags: [Group]
      summary: Add user to group
      description: Allows an existing group member to add another user to the conversation.
      operationId: addToGroup
      security:
        - BearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: User successfully added to the group
        '400':
          description: Invalid operation (e.g., user already in group)
        '404':
          description: Conversation or user not found

    delete:
      tags: [Group]
      summary: Remove a user from the group or leave group
      description: Allows a user to leave a conversation or removes a specified user.
      operationId: leaveGroup
      security:
        - BearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: User successfully removed from group
        '400':
          description: Invalid operation (e.g., user not in group)
        '404':
          description: Conversation or user not found


  /conversations/{conversationId}/name:
    put:
      tags:
        - Group
      summary: Change group name
      operationId: setGroupName
      security:
        - BearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Updated

  /conversations/{conversationId}/photo:
    put:
      tags:
        - Group
      summary: Set group photo
      operationId: setGroupPhoto
      security:
        - BearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - photo
              properties:
                photo:
                  type: string
                  format: byte
      responses:
        '200':
          description: Updated

  /user/photo:
    put:
      tags:
        - Profile
      summary: Set profile photo
      operationId: setMyPhoto
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - photo
              properties:
                photo:
                  type: string
                  format: byte
      responses:
        '200':
          description: Updated
  
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Username:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: "Alex"

    User:
      type: object
      required:
        - id
        - username
      properties:
        id:
          type: string
          example: "u1"
        username:
          $ref: '#/components/schemas/Username'
        profilePhoto:
          type: string
          format: byte
          nullable: true

    Reaction:
      type: object
      required:
        - type
        - authorId 
      properties:
        type:
          type: string
          enum: [like, heart, laugh,sad_face,angry_face]
        authorId:
          type: string
          example: "u1"

    Message:
      type: object
      required:
        - id
        - sender
        - content
        - timestamp
        - message_status
      properties:
        id:
          type: string
          example: "msg1"
        sender:
          $ref: '#/components/schemas/User'
        content:
          type: object
          required:
            - type
            - value
          properties:
            type:
              type: string
              enum: [text, photo]
            value:
              type: string
        timestamp:
          type: string
          format: date-time
        message_status:
          type: string
          enum: [sent, delivered, read]
        reactions:
          type: array
          items:
            $ref: '#/components/schemas/Reaction'
          nullable: true

    Conversation:
      type: object
      required:
        - id
        - name
        - isGroup
      properties:
        id:
          type: string
          example: "conv1"
        name:
          type: string
          example: "Chat"
        groupPhoto:
          type: string
          format: byte
          nullable: true
        isGroup:
          type: boolean
          example: true
        lastMessage:
          $ref: '#/components/schemas/Message'
          nullable: true
        participants:
          type: array
          items:
            $ref: '#/components/schemas/User'
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'
          nullable: true