openapi: 3.0.3
info:
  title: WASA-Exam
  description: Program that will hopefully pass the exam.
  version: 1.0.0

security: []   

tags:
  - name: Auth
    description: Endpoints for logging.
  - name: Profile
    description: Endpoints for managing user operations.
  - name: Conversation
    description: Endpoints for managing conversation operations.
  - name: Message
    description: Endpoints for managing message operations.
  - name: Reaction
    description: Endpoints for adding or removing reactions or comments on messages.
  - name: Group
    description: Endpoints for managing group operations.

paths:
  /doLogin:
    post:
      tags:
        - Auth
      summary: Log in or create an account
      description: |
        Logs in the user. 
        If the user doesn't exist, it will be created and an identifier is returned.
        If the user exists, the identifier is returned.
      operationId: doLogin
      security: []    
      requestBody:
        description: User details
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Maria
                  minLength: 3
                  maxLength: 16
              required: [name]
      responses:
        "200":
          description: User successfully logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    type: string
                    example: "abcdef012345"
        "201":
          description: User successfully created
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    type: string
                    example: "abcdef012345"
        "400":
          description: Invalid input data, failed to login
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid input data"

  /user/changename:
    put:
      tags:
        - Profile
      summary: Change your username
      description: Updates the username of the logged-in user if the new username is valid and not already taken.
      operationId: setMyUserName
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Username'
      responses:
        '200':
          description: Username updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid or already taken username
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Username already taken"


  /user/conversations:
    get:
      tags:
        - Conversation
      summary: Get user's conversations
      description: Returns all conversations of the logged-in user
      operationId: getMyConversations
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of conversations of the user
          content:
            application/json:
              schema:
                description: Array of objects each representing a conversation
                type: array
                items:
                  $ref: '#/components/schemas/Conversations'
        '400':
          description: Failed to retrieve conversations
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Failed to retrieve conversations"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User: 
      type: object
      description: Represents a user
      required:
        - id
        - username
      properties:
        id:
          type: string
          description: Unique identifier for the user, given upon account creation
          example: "user123"
          pattern: ^.*?$
          minLength: 1
          maxLength: 30
        username:
          $ref: '#/components/schemas/Username'
        profilePhoto:
          type: string
          format: byte
          description: Base64-encoded image data
          pattern: ^.*?$
          minLength: 0
          maxLength: 10485760
    Username:
      type: string
      minLength: 3
      maxLength: 20
      example: "Alex"

    Conversations:
      type: object
      description: Conversation belonging to a user
      properties:
        id:
          type: string
          example: "conv123"
        name:
          type: string
          example: "WASA Group Chat"
        isGroup:
          type: boolean
          description: True if this is a group conversation, false if private
          example: true
        lastMessage:
          type: string
          example: "What is a WASA exam?"
        participantsCount:
          type: integer
          example: 4
      required:
        - id
        - name
        - isGroup

