openapi: 3.0.3
info:
  title: WASA-Exam
  description: API for the WASA Exam project.
  version: 1.0.0

security: []

tags:
  - name: Auth
  - name: Profile
  - name: Conversation
  - name: Message
  - name: Reaction
  - name: Group

paths:
  /doLogin:
    post:
      tags:
        - Auth
      summary: Log in or create account
      operationId: doLogin
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  minLength: 3
                  maxLength: 20
                  example: "Maria"
      responses:
        "200":
          description: Logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    type: string
                    example: "user123token"
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    type: string
        '400':
          description: Invalid input'
        '404':
          description: User not found'

  /user/{userId}/changename:
    put:
      tags:
        - Profile
      summary: Change username
      operationId: setMyUserName
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Username'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Error
        '404':
          description: User not found'

  /user/{userId}/conversations:
    get:
      tags:
        - Conversation
      summary: Get conversations
      operationId: getMyConversations
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List conversations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Conversation'
        '400':
          description: Error'
        '404':
          description: User not found'

  /conversation/{id}:
    get:
      tags:
        - Conversation
      summary: Get single conversation
      operationId: getConversation
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conversation'
        '404':
          description: Conversation not found'
        '400':
          description: Error'

  /conversation/{id}/sendMessage:
    post:
      tags:
        - Message
      summary: Send message
      operationId: sendMessage
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: object
                  required:
                    - type
                    - value
                  properties:
                    type:
                      type: string
                      enum: [text, photo]
                    value:
                      type: string
      responses:
        '201':
          description: Sent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '400':
          description: Error'
        '404':
          description: Conversation not found'

  /conversation/{conversationId}/messages/{messageId}:
    delete:
      tags:
        - Message
      summary: Delete message
      operationId: deleteMessage
      security:
        - BearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
        - name: messageId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Deleted
        '400':
          description: Error'
        '404':
          description: Conversation or message not found'

  /conversation/{sourceConversationId}/messages/{messageId}/forward:
    post:
      tags:
        - Message
      summary: Forward message
      operationId: forwardMessage
      security:
        - BearerAuth: []
      parameters:
        - name: sourceConversationId
          in: path
          required: true
          schema:
            type: string
        - name: messageId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - targetConversationId
              properties:
                targetConversationId:
                  type: string
      responses:
        '201':
          description: Forwarded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '400':
          description: Error'
        '404':
          description: Conversation or message not found'

  /conversations/{conversationId}/messages/{messageId}/reactions:
    post:
      tags:
        - Reaction
      summary: Add reaction
      operationId: addReaction
      security:
        - BearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
        - name: messageId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - type
              properties:
                type:
                  type: string
                  enum: [like, heart, laugh]
      responses:
        '200':
          description: Reaction added or updated successfully. Returns the updated summary of reactions on the message.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reaction' 
        '400':
          description: Invalid reaction type provided or bad request data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid reaction type or data"
        '404':
          description: Conversation or message not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Message not found"

  /conversations/{conversationId}/messages/{messageId}/reactions/{type}:
    delete:
      tags:
        - Reaction
      summary: Remove reaction
      operationId: removeReaction
      security:
        - BearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
        - name: messageId
          in: path
          required: true
          schema:
            type: string
        - name: type
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Removed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '400':
          description: Error
        '404':
          description: Conversation or message not found'

  /conversations/{conversationId}/participants/{userId}:
    put:
      tags:
        - Group
      summary: Add user to group
      operationId: addToGroup
      security:
        - BearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Added
        '400':
          description: Error'
    delete:
      tags:
        - Group
      summary: Leave group
      operationId: leaveGroup
      security:
        - BearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Left
        '400':
          description: Error'
        '404':
          description: Conversation not found'

  /conversations/{conversationId}/name:
    put:
      tags:
        - Group
      summary: Change group name
      operationId: setGroupName
      security:
        - BearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Updated
        '400':
          description: Error'
        '404':
          description: Conversation not found'

  /conversations/{conversationId}/photo:
    put:
      tags:
        - Group
      summary: Set group photo
      operationId: setGroupPhoto
      security:
        - BearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - photo
              properties:
                photo:
                  type: string
                  format: byte
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conversation'
        '400':
          description: Error'
        '404':
          description: Conversation not found'

  /user/{userId}/photo:
    put:
      tags:
        - Profile
      summary: Set profile photo
      operationId: setMyPhoto
      security:
        - BearerAuth: []
          
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - photo
              properties:
                photo:
                  type: string
                  format: byte
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Error'
        '404':
          description: User not found'
  
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Username:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: "Alex"

    User:
      type: object
      required:
        - id
        - username
      properties:
        id:
          type: string
          example: "u1"
        username:
          $ref: '#/components/schemas/Username'
        profilePhoto:
          type: string
          format: byte
          nullable: true

    Reaction:
      type: object
      required:
        - type
        - authorId 
      properties:
        type:
          type: string
          enum: [like, heart, laugh]
        authorId:
          type: string
          example: "u1"

    Message:
      type: object
      required:
        - id
        - sender
        - content
        - timestamp
        - message_status
      properties:
        id:
          type: string
          example: "msg1"
        sender:
          $ref: '#/components/schemas/User'
        content:
          type: object
          required:
            - type
            - value
          properties:
            type:
              type: string
              enum: [text, photo]
            value:
              type: string
        timestamp:
          type: string
          format: date-time
        message_status:
          type: string
          enum: [sent, delivered, read]
        reactions:
          type: array
          items:
            $ref: '#/components/schemas/Reaction'
          nullable: true

    Conversation:
      type: object
      required:
        - id
        - name
        - isGroup
      properties:
        id:
          type: string
          example: "conv1"
        name:
          type: string
          example: "Chat"
        groupPhoto:
          type: string
          format: byte
          nullable: true
        isGroup:
          type: boolean
          example: true
        lastMessage:
          $ref: '#/components/schemas/Message'
          nullable: true
        participants:
          type: array
          items:
            $ref: '#/components/schemas/User'
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'
          nullable: true