openapi: 3.0.3
info:
  title: WASA-Exam
  description: API for the WASA Exam project.
  version: 1.0.0

security: []

tags:
  - name: Auth
  - name: Profile
  - name: Conversation
  - name: Message
  - name: Reaction
  - name: Group

paths:
  /login:
    post:
      tags:
        - Auth
      summary: Log in or create account
      operationId: doLogin
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  minLength: 3
                  maxLength: 20
                  example: "Maria"
      responses:
        "200":
          description: Logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    type: string
                    example: "user123token"
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    type: string

  /users:
    get:
      tags:
        - Profile
      summary: Get all users
      operationId: getAllUsers
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                    $ref: '#/components/schemas/User'

  /searchby:
    get:
      tags:
        - Profile
      summary: Search users
      operationId: searchBy
      parameters:
        - name: user
          in: query
          description: Username to search for
          schema:
            type: string
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of matching users
          content:
            application/json:
              schema:
                type: array
                items:
                    $ref: '#/components/schemas/User'

  /user/username:
    put:
      tags:
        - Profile
      summary: Change username
      operationId: setMyUserName
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Username'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Error

  /user/photo:
    put:
      tags:
        - Profile
      summary: Set profile photo
      operationId: setMyPhoto
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - photo
              properties:
                photo:
                  type: string
                  format: byte
      responses:
        '200':
          description: Updated
  
  /conversations:
    get:
      tags:
        - Conversation
      summary: Get conversations
      operationId: getMyConversations
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List conversations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Conversation'

  /conversations/{conversationId}:
    get:
      tags:
        - Conversation
      summary: Get single conversation
      operationId: getConversation
      security:
        - BearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conversation'
    delete:
      tags:
        - Conversation
      summary: Delete or leave a conversation
      operationId: deleteConversation
      security:
        - BearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Deleted/Left successfully

  /conversations/{conversationId}/members:
    get:
        tags:
            - Conversation
        summary: Get conversation members
        operationId: getConversationMembers
        security:
            - BearerAuth: []
        parameters:
            - name: conversationId
              in: path
              required: true
              schema:
                type: string
        responses:
            '200':
                description: List of members
                content:
                    application/json:
                        schema:
                            type: array
                            items:
                                $ref: '#/components/schemas/User'

  /direct-conversations:
    post:
        tags:
            - Conversation
        summary: Create or get direct conversation
        operationId: createDirectConversation
        security:
            - BearerAuth: []
        requestBody:
            required: true
            content:
                application/json:
                    schema:
                        type: object
                        required: [peerUserId]
                        properties:
                            peerUserId:
                                type: string
        responses:
            '201':
                description: Conversation created/retrieved
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Conversation'

  /conversations/{conversationId}/messages:
    post:
      tags:
        - Message
      summary: Send message
      operationId: sendMessage
      security:
        - BearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: object
                  required:
                    - type
                    - value
                  properties:
                    type:
                      type: string
                      enum: [text, photo]
                    value:
                      type: string
      responses:
        '201':
          description: Sent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'

  /conversations/{conversationId}/messages/{messageId}:
    delete:
      tags:
        - Message
      summary: Delete message
      operationId: deleteMessage
      security:
        - BearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
        - name: messageId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Deleted

  /conversations/{conversationId}/messages/{messageId}/forward:
    post:
      tags:
        - Message
      summary: Forward message
      operationId: forwardMessage
      security:
        - BearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
        - name: messageId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - targetConversationId
              properties:
                targetConversationId:
                  type: string
      responses:
        '201':
          description: Forwarded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
  
  /conversations/{conversationId}/messages/{messageId}/status:
    post:
      tags:
        - Message
      summary: Set message status
      operationId: setMessageStatus
      security:
        - BearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
        - name: messageId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [status]
              properties:
                status:
                  type: string
                  enum: [delivered, read]
      responses:
        '200':
          description: Status updated

  /conversations/{conversationId}/messages/{messageId}/reaction:
    post:
      tags: [Reaction]
      summary: Add a reaction to a message
      operationId: addReaction
      security:
        - BearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
        - name: messageId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [type]
              properties:
                type:
                  type: string
                  enum: [like, heart, laugh,sad_face,angry_face]
                  description: Type of reaction to add
      responses:
        '200':
          description: Reaction added successfully
        '400':
          description: Invalid request 
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid reaction"
        '404':
          description: Message or conversation not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Message not found"

    delete:
      tags: [Reaction]
      summary: Remove a reaction from a message
      operationId: removeReaction
      security:
        - BearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
        - name: messageId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
            application/json:
                schema:
                    type: object
                    required: [type]
                    properties:
                        type:
                            type: string
                            enum: [like, heart, laugh,sad_face,angry_face]
      responses:
        '200':
          description: Reaction removed successfully
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Message or conversation not found

  /groups:
    post:
        tags: [Group]
        summary: Create a group
        operationId: createGroup
        security:
            - BearerAuth: []
        requestBody:
            required: true
            content:
                application/json:
                    schema:
                        type: object
                        required: [groupName, members]
                        properties:
                            groupName:
                                type: string
                            members:
                                type: array
                                items:
                                    type: string
                            groupPhoto:
                                type: string
                                format: byte
        responses:
            '201':
                description: Group created
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Conversation'

  /groups/{groupId}:
    post:
        tags: [Group]
        summary: Add user to group
        operationId: addToGroup
        security:
            - BearerAuth: []
        parameters:
            - name: groupId
              in: path
              required: true
              schema:
                type: string
        requestBody:
            required: true
            content:
                application/json:
                    schema:
                        type: object
                        required: [userId]
                        properties:
                            userId:
                                type: string
        responses:
            '204':
                description: User added

    delete:
        tags: [Group]
        summary: Remove user from group (or leave if self)
        operationId: leaveGroup
        security:
            - BearerAuth: []
        parameters:
            - name: groupId
              in: path
              required: true
              schema:
                type: string
        requestBody:
            required: true
            content:
                application/json:
                    schema:
                        type: object
                        required: [userId]
                        properties:
                            userId:
                                type: string
        responses:
            '204':
                description: User removed

  /groups/{groupId}/name:
    put:
      tags:
        - Group
      summary: Change group name
      operationId: setGroupName
      security:
        - BearerAuth: []
      parameters:
        - name: groupId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Updated

  /groups/{groupId}/photo:
    put:
      tags:
        - Group
      summary: Set group photo
      operationId: setGroupPhoto
      security:
        - BearerAuth: []
      parameters:
        - name: groupId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - photo
              properties:
                photo:
                  type: string
                  format: byte
      responses:
        '200':
          description: Updated

  /liveness:
    get:
        tags: [System]
        summary: Health check
        operationId: liveness
        responses:
            '200':
                description: OK
  
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Username:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: "Alex"

    User:
      type: object
      required:
        - id
        - username
      properties:
        id:
          type: string
          example: "u1"
        username:
          $ref: '#/components/schemas/Username'
        profilePhoto:
          type: string
          format: byte
          nullable: true

    Reaction:
      type: object
      required:
        - type
        - authorId 
      properties:
        type:
          type: string
          enum: [like, heart, laugh,sad_face,angry_face]
        authorId:
          type: string
          example: "u1"

    Message:
      type: object
      required:
        - id
        - sender
        - content
        - timestamp
        - message_status
      properties:
        id:
          type: string
          example: "msg1"
        sender:
          $ref: '#/components/schemas/User'
        content:
          type: object
          required:
            - type
            - value
          properties:
            type:
              type: string
              enum: [text, photo]
            value:
              type: string
        timestamp:
          type: string
          format: date-time
        message_status:
          type: string
          enum: [sent, delivered, read]
        forwarded_from:
          type: string
          nullable: true
        reactions:
          type: array
          items:
            $ref: '#/components/schemas/Reaction'
          nullable: true

    Conversation:
      type: object
      required:
        - id
        - name
        - isGroup
      properties:
        id:
          type: string
          example: "conv1"
        name:
          type: string
          example: "Chat"
        groupPhoto:
          type: string
          format: byte
          nullable: true
        isGroup:
          type: boolean
          example: true
        lastMessage:
          allOf:
            - $ref: '#/components/schemas/Message'
          nullable: true
        participants:
          type: array
          items:
            $ref: '#/components/schemas/User'
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'
          nullable: true